### ISSUE TITLE
[Question] How do you develop?

### ISSUE THREAD

**Issue by tfrijsewijk** [nathansearles/react-flex-grid#2]
Hi,

I found your package through tsdx dependents and I was wondering: How do you develop this package? I don't see any .html files around.

I'm developing a Leaflet plugin and I started out with tsdx, but it was too cumbersome to actually develop it. I tried with a rollup dev server plugin, which worked below expectation due to TSDX's compilation strategy.

Just now I converted my plugin to `klap` but I'm a bit hestitant because it only has 250 downloads a week vs 10000+ downloads with TSDX.

So.. How do you develop? :)

Thanks!
Thomas

**Comment by nathansearles** [comment]
Hey! Sorry, somehow I missed your question.

I have two branches, main, and examples: https://github.com/nathansearles/react-flex-grid/tree/examples. Examples is just the example site built with [Next.js](https://nextjs.org/): https://react-flex-grid.vercel.app/. Although I'm likely to switch this around and integrated examples into the main branch.

Check out the [package.com](https://github.com/nathansearles/react-flex-grid/blob/master/package.json), I used [tsdx](https://www.npmjs.com/package/tsdx) with [Rollup](https://www.npmjs.com/package/rollup). Seemed like the most straight forward solution to me.

Hope that helps!
